_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    OUTPUT_LAYER: "CosineSimOutputLayers"
    NUM_CLASSES: 20
    BATCH_SIZE_PER_IMAGE: 512
DATALOADERS:
  NUM_WORKERS: 2
DATASETS:
  TRAIN: ('dior_5shot',)
  TEST: ('dior_test',)
SOLVER:
  STEPS: (4000,)
  MAX_ITER: 5000
  CHECKPOINT_PERIOD: 10000
SIS:
  NUM_AUGMENTATION : 1
TEST:
  PCB_ENABLE: False
  PCB_MODELPATH: "./ImageNetPretrained/torchvision/resnet101-5d3b4d8f.pth"
  PCB_ALPHA : 0.0
  PCB_MODELTYPE : 'resnet'